module.exports = {
    VIEW_SET: 'VIEW_SET',
    // export const NAV_LOG: 'NAV_LOG'

    KEYBOARD_TOGGLE: 'KEYBOARD_TOGGLE',
    MOUSE_TOGGLE: 'MOUSE_TOGGLE',

    WS_KEY_PRESS: 'WS_KEY_PRESS',
    WS_KEY_TOGGLE: 'WS_KEY_TOGGLE',
    WS_MOUSE_CLICK: 'WS_MOUSE_CLICK',
    WS_MOUSE_MOVE: 'WS_MOUSE_MOVE',
    WS_MOUSE_TOGGLE: 'WS_MOUSE_TOGGLE',
    WS_MOUSE_DRAG: 'WS_MOUSE_DRAG',

    WS_CLIPBOARD_PULL: 'WS_CLIPBOARD_PULL',
    WS_CLIPBOARD_PUSH: 'WS_CLIPBOARD_PUSH',

    UPLOAD_FILE_COMPLETED: 'UPLOAD_FILE_COMPLETED',
}
